apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: garouter-uaa
  namespace: gopal
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: garouter
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - "https://garouter.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com/login/callback"
    scopes:
      - name: "$XSAPPNAME.admin"
        description: Admin
    role-templates:
      - name: admin
        description: Admin
        scope-references:
          - "$XSAPPNAME.admin"
---

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: routerauth-binding
  namespace: gopal
spec:
  instanceRef:
    name: garouter-uaa
  secretName: routerauth-binding
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gopal
  name: garouter
  labels:
    app: garouter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garouter
      version: v1
  template:
    metadata:
      namespace: gopal
      labels:
        app: garouter
        version: v1
    spec:
      containers:
        - name: garouter
          image: gopalanand/garouter:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: garouter-uaa
              mountPath: "/etc/secrets/sapcp/xsuaa/garouter-uaa"
              readOnly: true
      volumes:
        - name: garouter-uaa
          secret:
            secretName: routerauth-binding
---
apiVersion: v1
kind: Service
metadata:
  namespace: gopal
  name: garouter
  labels:
    app: garouter
    service: garouter
spec:
  ports:
    - port: 5000
      name: http
  selector:
    app: garouter

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: garouter
  namespace: gopal
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: garouter.d6c9019.kyma-stage.shoot.live.k8s-hana.ondemand.com
    name: garouter
    port: 5000
#