version: '3.4'

services:
  approuter:
    image: approuter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "node_modules/@sap/approuter/approuter.js"]
